### ISSUE TITLE
Week 1: Name your Cat

### ISSUE THREAD

**Issue by ganning127** [ganning127/test9#2]
Week 1 Step 7 ⬤⬤⬤⬤⬤⬤⬤◯◯ | 🕐 Estimated completion: 5-15 minutes
## ✅  Task:
- [ ] Run `git pull`
- [ ] ***1:*** Modify your Azure Function to output TWO generated cat pictures from the cat API and TWO random names from list below:
    - "Shreya, Emily, Fifi, Beau, Evelyn, Julia, Daniel, Fardeen"
    - Use the CataaS API endpoint: https://cataas.com/cat/cute/says/Bitcamp
- [ ] ***2:*** Return the images, encoded in **base64**, and names in **JSON format** in the body
    ```js
    body: {
        cat1: your-first-catpicture-in-base64,
        cat2: your-second-catpicture-in-base64,
        names: [name1, name2]
    }
    ```
- [ ] 🚀 Commit your updated function code in `twocatz/index.js` to the `twocatz` branch

> :exclamation: **Do not merge the branch!!**

## 🚧 Test your Work
When you paste your **Function URL** in your browser or make a GET request with **Postman**, you might get something like:
```json
{
  "cat1": "/9j/4AAQSk...",
  "cat2": "R0lGODlhCwHI...",
   "names": [
    "Daniel",
    "Shreya"
  ]
```

## 1: Select random items out of a list

1. Create an array with the names first
2. Generate a random number within the range of the array length

<details>
<summary>:exclamation: How do I generate two random names?</summary>
    </br>

1. Create an array with the names:
```js
let names = ["name1", "name2"...]
```

2. Generate a random value in the correct range:
```js
let random_value = Math.floor(names.length * Math.random())
```

3. Get the name!
```js
let resultname = names[random_value]
```

4. Wrap the code for generating a random combination into a function that returns resultname and call the function twice to get two names!

<br><br/>
</details>

## 2: Return images in JSON format

`context.res` is the key to answering this question!

<details>
<summary>:exclamation: How do I return the images using context.res?</summary>
    </br>

To return your two images and two names in the output:
```js
context.res = {
    body: {
        cat1: your-first-catpicture-in-base64,
        cat2: your-second-catpicture-in-base64,
        names: [name1, name2]
    }
}
```
<br><br/>
</details>
